### ISSUE TITLE
Bug: ValueError: badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by vnfmsqkek3** [aws-deadline/deadline-cloud-for-blender#112]
### Expected Behaviour

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 1515, in _readerthread
    buffer.append(fh.read())
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 200: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\api\_telemetry.py", line 172, in _get_telemetry_identifier
    uuid.UUID(identifier, version=4)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\addons\deadline_cloud_blender_submitter\__init__.py", line 104, in invoke
    return self.execute(context)
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\addons\deadline_cloud_blender_submitter\__init__.py", line 72, in execute
    self.widget = create_deadline_dialog()
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\addons\deadline_cloud_blender_submitter\open_deadline_cloud_dialog.py", line 38, in create_deadline_dialog
    api.get_deadline_cloud_library_telemetry_client().update_common_details(
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\api\_telemetry.py", line 351, in get_deadline_cloud_library_telemetry_client
    return get_telemetry_client("deadline-cloud-library", version, config=config)
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\api\_telemetry.py", line 332, in get_telemetry_client
    __cached_telemetry_client = TelemetryClient(
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\api\_telemetry.py", line 97, in __init__
    self.telemetry_id: str = self._get_telemetry_identifier(config=config)
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\api\_telemetry.py", line 175, in _get_telemetry_identifier
    config_file.set_setting("telemetry.identifier", identifier)
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\config\config_file.py", line 426, in set_setting
    write_config(config)
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\config\config_file.py", line 279, in write_config
    _reset_directory_permissions_windows(config_file_parent_path, username, "(OI)(CI)(F)")
  File "C:\Users\jaehyeok\DeadlineCloudSubmitter\Submitters\Blender\python\modules\deadline\client\config\config_file.py", line 214, in _reset_directory_permissions_windows
    for line in icacls_output.splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

I successfully added the DeadlineCloudSubmitter as an addon in Blender, but an error occurs when I run it.

blender : v3.6.12

### Current Behaviour

OS : Window 11 x64
install : DeadlineCloudSubmitter-2024.05.31.0-windows-x64-installer

### Reproduction Steps

Running it with administrator privileges doesn't work, and I tried various installation paths, but it still failed.

### Code Snippet

.

**Comment by vnfmsqkek3** [comment]
aws configure

**Comment by lunacava** [comment]
Hi, @vnfmsqkek3  have you managed to solve this problem? and how?
I got a same probrem with windows 10 enviroment.
with "DeadlineCloudSubmitter-2024.10.21.0-windows-x64-installer"
blender 3.6.10
![image](https://github.com/user-attachments/assets/05b4d398-93b7-4249-a274-1908fba22ff7)

how did you fix this error?
